[package]
name = "rstd"
version = "0.2.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
strum = "0.26"
strum_macros = "0.26"
rusqlite = { version = "0.37.0", features = ["bundled"] }
ratatui = { version = "0.29.0", features = ["all-widgets"] }
crossterm = "0.29.0"
thiserror = "2.0.17"
